### Global EKF (map -> odom) ###
ekf_filter_node_global:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map  # Globalはmap座標系が基準

    # LiDAR Odometry (Localと同じ)
    odom0: /odom
    odom0_config: [true,  true,  true,
                   true,  true,  true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false

    # IMU (Localと同じ)
    imu0: /wit/imu
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_differential: false
    imu0_relative: false # Globalでは絶対方位(Heading)を信じる

    # GPS (navsat_transform_nodeからの出力)
    odom1: /odometry/gps
    odom1_config: [true,  true,  false,  # X, Y (Zは信頼しない場合false)
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom1_differential: false
    odom1_relative: false